# -*- coding: utf-8 -*-
"""parsing_distribution.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeKPsWW_e6-oeuBKuC9YuQdbJcTXv9KW
"""

import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("nvidia_news_final_20251106_020225.csv")

categories = {
    "financial_results": [
            (r"\bbeat\s+estimate\w*\b", 3.0),
            (r"\bmiss\s+estimate\w*\b", 3.0),
            (r"\bguidance\b", 3.0),
            (r"\bforecast\w*\b", 3.0),
            (r"\bquarterly\s+report\w*\b", 3.0),
            (r"\bannual\s+result\w*\b", 3.0),
            (r"\bearnings?\s+call\b", 3.0),
            (r"\bprofit\s+warning\b", 3.0),
            (r"\bdividend\s+announcement\b", 3.0),
            (r"\binterim\s+dividend\b", 3.0),
            (r"\bfinal\s+dividend\b", 3.0),
            (r"\bbuyback\b", 3.0),
            (r"\brepurchase\b", 3.0),
            (r"\bEPS\b", 3.0),
            (r"\bEBITDA\b", 3.0),
            (r"\bnet\s+income\w*\b", 3.0),
            (r"\boperating\s+profit\b", 3.0),

            (r"\brevenue\w*\b", 1.0),
            (r"\bprofit\w*\b", 1.0),
            (r"\bearn\w*\b", 1.0),
            (r"\bmargin\w*\b", 1.0),
            (r"\bcash\s+flow\w*\b", 1.0),
            (r"\bfree\s+cash\s+flow\b", 1.0),
            (r"\bdebt\w*\b", 1.0),
            (r"\bbalance\s+sheet\w*\b", 1.0),
            (r"\bincome\s+statement\b", 1.0),
            (r"\bP&L\b", 1.0),
            (r"\bprofit\w*\s+loss\b", 1.0),

            (r"\bfinancial\w*\b", 0.3),
            (r"\baccount\w*\b", 0.3),
            (r"\bconsolidat\w*\b", 0.3),
            (r"\bamortiz\w*\b", 0.3),
            (r"\bdepreciat\w*\b", 0.3),
            (r"\bgoodwill\b", 0.3),
            (r"\bsecurit\w*\b", 0.3),
            (r"\bderivative\w*\b", 0.3),
            #слова шумы
        (r"\brumour?\w*\b", -1.5),
        (r"\bhearsay\b", -1.5),
        (r"\bunconfirmed\b", -1.5),
        (r"\balleged\w*\b", -1.5),
        (r"\bwhisper\w*\b", -1.5),
        (r"\bgossip\w*\b", -1.5),
        (r"\bchatter\b", -1.5),

        (r"\bmight\b", -1.0),
        (r"\bcould\b", -1.0),
        (r"\bwould\b", -1.0),
        (r"\bshould\b", -1.0),
        (r"\bpossibly\b", -1.0),
        (r"\bpotentially\b", -1.0),
        (r"\bperhaps\b", -1.0),
        (r"\bmaybe\b", -1.0),
        (r"\bunlikely\b", -1.0),
        (r"\bdoubtful\b", -1.0),
        (r"\buncertain\w*\b", -1.0),

        (r"\bcommentary\b", -0.7),
        (r"\bopinion\w*\b", -0.7),
        (r"\bview\w*\b", -0.7),
        (r"\bperspective\w*\b", -0.7),
        (r"\boutlook\b", -0.7),
        (r"\bassessment\b", -0.7),
        (r"\bevaluation\b", -0.7),
        (r"\bappraisal\b", -0.7),

        (r"\bresistance\b", -0.5),
        (r"\bsupport\b", -0.5),
        (r"\bmoving average\b", -0.5),
        (r"\bRSI\b", -0.5),
        (r"\bMACD\b", -0.5),
        (r"\bBollinger\b", -0.5),
        (r"\bfibonacci\b", -0.5),
        (r"\bchart pattern\w*\b", -0.5),
        (r"\btechnical indicator\w*\b", -0.5),



        (r"\beventually\b", -0.3),
        (r"\bin the future\b", -0.3),
        (r"\bdown the road\b", -0.3),
        (r"\bin coming years\b", -0.3),
        (r"\blong.term\b", -0.3),
        (r"\bfuture prospect\w*\b", -0.3),
        (r"\bpotential growth\b", -0.3),
        ],

    "product_launches": [
            (r"\blaunch\w*\b", 3.0),
            (r"\breleas\w*\b", 3.0),
            (r"\bannounc\w*\b", 3.0),
            (r"\bunveil\w*\b", 3.0),
            (r"\bintroduc\w*\b", 3.0),
            (r"\bdebut\w*\b", 3.0),
            (r"\bpremier\w*\b", 3.0),
            (r"\bbreakthrough\w*\b", 3.0),
            (r"\brevolution\w*\b", 3.0),
            (r"\bgame.changer\b", 3.0),
            (r"\bindustry.first\b", 3.0),
            (r"\bHopper\b", 3.0),
            (r"\bBlackwell\b", 3.0),
            (r"\bGrace\b", 3.0),
            (r"\bDGX\s+\w+\b", 3.0),
            (r"\bHGX\s+\w+\b", 3.0),
            (r"\bGH200\b", 3.0),

            (r"\bproduct\w*\b", 1.0),
            (r"\bplatform\w*\b", 1.0),
            (r"\bframework\w*\b", 1.0),
            (r"\barchitecture\w*\b", 1.0),
            (r"\bgeneration\w*\b", 1.0),
            (r"\bmodel\w*\b", 1.0),
            (r"\bseries\w*\b", 1.0),
            (r"\bAI\b", 1.0),
            (r"\bartificial\s+intelligence\b", 1.0),
            (r"\bmachine\s+learning\b", 1.0),
            (r"\bdeep\s+learning\b", 1.0),
            (r"\bneural\s+network\w*\b", 1.0),
            (r"\bCUDA\b", 1.0),
            (r"\bOmniverse\b", 1.0),
            (r"\bJetson\b", 1.0),
            (r"\bRTX\b", 1.0),
            (r"\bGeforce\b", 1.0),

            (r"\binnov\w*\b", 0.3),
            (r"\bupdat\w*\b", 0.3),
            (r"\bprototype\w*\b", 0.3),
            (r"\bbeta\w*\b", 0.3),
            (r"\bdeploy\w*\b", 0.3),
            (r"\bdebug\w*\b", 0.3),
            (r"\bchip\w*\b", 0.3),
            (r"\bgpu\w*\b", 0.3),
            (r"\baccelerat\w*\b", 0.3),
            #слова шумы
        (r"\brumour?\w*\b", -1.5),
        (r"\bhearsay\b", -1.5),
        (r"\bunconfirmed\b", -1.5),
        (r"\balleged\w*\b", -1.5),
        (r"\bwhisper\w*\b", -1.5),
        (r"\bgossip\w*\b", -1.5),
        (r"\bchatter\b", -1.5),

        (r"\bmight\b", -1.0),
        (r"\bcould\b", -1.0),
        (r"\bwould\b", -1.0),
        (r"\bshould\b", -1.0),
        (r"\bpossibly\b", -1.0),
        (r"\bpotentially\b", -1.0),
        (r"\bperhaps\b", -1.0),
        (r"\bmaybe\b", -1.0),
        (r"\bunlikely\b", -1.0),
        (r"\bdoubtful\b", -1.0),
        (r"\buncertain\w*\b", -1.0),

        (r"\bcommentary\b", -0.7),
        (r"\bopinion\w*\b", -0.7),
        (r"\bview\w*\b", -0.7),
        (r"\bperspective\w*\b", -0.7),
        (r"\boutlook\b", -0.7),
        (r"\bassessment\b", -0.7),
        (r"\bevaluation\b", -0.7),
        (r"\bappraisal\b", -0.7),

        (r"\bresistance\b", -0.5),
        (r"\bsupport\b", -0.5),
        (r"\bmoving average\b", -0.5),
        (r"\bRSI\b", -0.5),
        (r"\bMACD\b", -0.5),
        (r"\bBollinger\b", -0.5),
        (r"\bfibonacci\b", -0.5),
        (r"\bchart pattern\w*\b", -0.5),
        (r"\btechnical indicator\w*\b", -0.5),



        (r"\beventually\b", -0.3),
        (r"\bin the future\b", -0.3),
        (r"\bdown the road\b", -0.3),
        (r"\bin coming years\b", -0.3),
        (r"\blong.term\b", -0.3),
        (r"\bfuture prospect\w*\b", -0.3),
        (r"\bpotential growth\b", -0.3),
        ],

    "mergers_acquisitions": [
            (r"\bacquir\w*\b", 3.0),
            (r"\bmerg\w*\b", 3.0),
            (r"\btakeover\w*\b", 3.0),
            (r"\bbuyout\w*\b", 3.0),
            (r"\bM&A\b", 3.0),
            (r"\bacquire\w*\b", 3.0),
            (r"\bdeal\s+close\w*\b", 3.0),
            (r"\btransaction\s+complete\w*\b", 3.0),
            (r"\bapprov\w*\b", 3.0),
            (r"\bregulatory\s+approval\b", 3.0),
            (r"\bIPO\b", 3.0),
            (r"\bSPAC\b", 3.0),
            (r"\bleveraged\s+buyout\b", 3.0),
            (r"\bprivate\s+equity\b", 3.0),

            (r"\binvest\w*\b", 1.0),
            (r"\bventure\w*\b", 1.0),
            (r"\bjoint\s+venture\w*\b", 1.0),
            (r"\bpartnership\w*\b", 1.0),
            (r"\bstrategic\s+deal\w*\b", 1.0),
            (r"\bstake\w*\b", 1.0),
            (r"\bspin.off\w*\b", 1.0),
            (r"\bdivest\w*\b", 1.0),
            (r"\bconsolidat\w*\b", 1.0),
            (r"\bcollaborat\w*\b", 1.0),

            (r"\bfundrais\w*\b", 0.3),
            (r"\bterm\s+sheet\w*\b", 0.3),
            (r"\bshare\s+purchas\w*\b", 0.3),
            (r"\basset\s+purchas\w*\b", 0.3),
            (r"\bexit\w*\b", 0.3),
            #слова шумы
        (r"\brumour?\w*\b", -1.5),
        (r"\bhearsay\b", -1.5),
        (r"\bunconfirmed\b", -1.5),
        (r"\balleged\w*\b", -1.5),
        (r"\bwhisper\w*\b", -1.5),
        (r"\bgossip\w*\b", -1.5),
        (r"\bchatter\b", -1.5),

        (r"\bmight\b", -1.0),
        (r"\bcould\b", -1.0),
        (r"\bwould\b", -1.0),
        (r"\bshould\b", -1.0),
        (r"\bpossibly\b", -1.0),
        (r"\bpotentially\b", -1.0),
        (r"\bperhaps\b", -1.0),
        (r"\bmaybe\b", -1.0),
        (r"\bunlikely\b", -1.0),
        (r"\bdoubtful\b", -1.0),
        (r"\buncertain\w*\b", -1.0),

        (r"\bcommentary\b", -0.7),
        (r"\bopinion\w*\b", -0.7),
        (r"\bview\w*\b", -0.7),
        (r"\bperspective\w*\b", -0.7),
        (r"\boutlook\b", -0.7),
        (r"\bassessment\b", -0.7),
        (r"\bevaluation\b", -0.7),
        (r"\bappraisal\b", -0.7),

        (r"\bresistance\b", -0.5),
        (r"\bsupport\b", -0.5),
        (r"\bmoving average\b", -0.5),
        (r"\bRSI\b", -0.5),
        (r"\bMACD\b", -0.5),
        (r"\bBollinger\b", -0.5),
        (r"\bfibonacci\b", -0.5),
        (r"\bchart pattern\w*\b", -0.5),
        (r"\btechnical indicator\w*\b", -0.5),



        (r"\beventually\b", -0.3),
        (r"\bin the future\b", -0.3),
        (r"\bdown the road\b", -0.3),
        (r"\bin coming years\b", -0.3),
        (r"\blong.term\b", -0.3),
        (r"\bfuture prospect\w*\b", -0.3),
        (r"\bpotential growth\b", -0.3),
        ],

    "regulatory_legal":[
            (r"\bfine\w*\b", 3.0),
            (r"\bpenalt\w*\b", 3.0),
            (r"\bsanction\w*\b", 3.0),
            (r"\bverdict\w*\b", 3.0),
            (r"\bruling\w*\b", 3.0),
            (r"\bjudgment\w*\b", 3.0),
            (r"\bantitrust\w*\b", 3.0),
            (r"\bDOJ\b", 3.0),
            (r"\bSEC\b", 3.0),
            (r"\bFTC\b", 3.0),
            (r"\binvestigat\w*\b", 3.0),
            (r"\blawsuit\w*\b", 3.0),
            (r"\blitigation\w*\b", 3.0),
            (r"\bclass\s+action\w*\b", 3.0),
            (r"\bsettlement\w*\b", 3.0),

            (r"\bcourt\w*\b", 1.0),
            (r"\btrial\w*\b", 1.0),
            (r"\blegal\w*\b", 1.0),
            (r"\battorney\w*\b", 1.0),
            (r"\bappeal\w*\b", 1.0),
            (r"\bregulat\w*\b", 1.0),
            (r"\blicens\w*\b", 1.0),
            (r"\bcompliance\w*\b", 1.0),
            (r"\bviolat\w*\b", 1.0),

            (r"\bjurisdiction\w*\b", 0.3),
            (r"\bcontract\w*\b", 0.3),
            (r"\bagreement\w*\b", 0.3),
            (r"\bbreach\w*\b", 0.3),
            (r"\bsummon\w*\b", 0.3),
            (r"\bsue\w*\b", 0.3),

            #слова добавленные
            (r"\binflation\w*\b", 3.0),
            (r"\brecession\w*\b", 3.0),
            (r"\bcrisis\w*\b", 3.0),
            (r"\binterest\s+rate\w*\b", 3.0),
            (r"\bmonetary\s+policy\b", 3.0),
            (r"\bchip\s+shortage\w*\b", 3.0),
            (r"\bsupply\s+chain\w*\b", 3.0),
            (r"\btariff\w*\b", 3.0),
            (r"\btrade\s+war\w*\b", 3.0),
            (r"\bgeopolitical\w*\b", 3.0),

            (r"\bGDP\s+growth\b", 1.0),
            (r"\bunemployment\s+rate\w*\b", 1.0),
            (r"\bexchange\s+rate\w*\b", 1.0),
            (r"\bconsumer\s+spending\b", 1.0),
            (r"\bfiscal\s+policy\b", 1.0),
            (r"\bcentral\s+bank\w*\b", 1.0),
            (r"\bquantitative\s+easing\b", 1.0),

            (r"\bcommodity\s+price\w*\b", 0.3),
            (r"\braw\s+material\w*\b", 0.3),
            (r"\binvestment\s+inflow\w*\b", 0.3),
            (r"\boutflow\w*\b", 0.3),
            (r"\bpublic\s+debt\b", 0.3),
            (r"\bbudget\s+deficit\w*\b", 0.3),
            #слова шумы
        (r"\brumour?\w*\b", -1.5),
        (r"\bhearsay\b", -1.5),
        (r"\bunconfirmed\b", -1.5),
        (r"\balleged\w*\b", -1.5),
        (r"\bwhisper\w*\b", -1.5),
        (r"\bgossip\w*\b", -1.5),
        (r"\bchatter\b", -1.5),

        (r"\bmight\b", -1.0),
        (r"\bcould\b", -1.0),
        (r"\bwould\b", -1.0),
        (r"\bshould\b", -1.0),
        (r"\bpossibly\b", -1.0),
        (r"\bpotentially\b", -1.0),
        (r"\bperhaps\b", -1.0),
        (r"\bmaybe\b", -1.0),
        (r"\bunlikely\b", -1.0),
        (r"\bdoubtful\b", -1.0),
        (r"\buncertain\w*\b", -1.0),

        (r"\bcommentary\b", -0.7),
        (r"\bopinion\w*\b", -0.7),
        (r"\bview\w*\b", -0.7),
        (r"\bperspective\w*\b", -0.7),
        (r"\boutlook\b", -0.7),
        (r"\bassessment\b", -0.7),
        (r"\bevaluation\b", -0.7),
        (r"\bappraisal\b", -0.7),

        (r"\bresistance\b", -0.5),
        (r"\bsupport\b", -0.5),
        (r"\bmoving average\b", -0.5),
        (r"\bRSI\b", -0.5),
        (r"\bMACD\b", -0.5),
        (r"\bBollinger\b", -0.5),
        (r"\bfibonacci\b", -0.5),
        (r"\bchart pattern\w*\b", -0.5),
        (r"\btechnical indicator\w*\b", -0.5),



        (r"\beventually\b", -0.3),
        (r"\bin the future\b", -0.3),
        (r"\bdown the road\b", -0.3),
        (r"\bin coming years\b", -0.3),
        (r"\blong.term\b", -0.3),
        (r"\bfuture prospect\w*\b", -0.3),
        (r"\bpotential growth\b", -0.3),
        ],

    "scandals": [
            (r"\bfraud\w*\b", 3.0),
            (r"\bembezzl\w*\b", 3.0),
            (r"\bbrib\w*\b", 3.0),
            (r"\bcorrupt\w*\b", 3.0),
            (r"\binsider\s+trad\w*\b", 3.0),
            (r"\bmoney\s+laund\w*\b", 3.0),
            (r"\btax\s+evad\w*\b", 3.0),
            (r"\bscandal\w*\b", 3.0),
            (r"\bcover.up\w*\b", 3.0),
            (r"\bwhistleblow\w*\b", 3.0),
            (r"\bmisconduct\w*\b", 3.0),

            (r"\bfalsif\w*\b", 1.0),
            (r"\bforg\w*\b", 1.0),
            (r"\bcheat\w*\b", 1.0),
            (r"\bscam\w*\b", 1.0),
            (r"\bdecept\w*\b", 1.0),
            (r"\bmanipulat\w*\b", 1.0),
            (r"\bdata\s+leak\w*\b", 1.0),
            (r"\bprivacy\s+breach\w*\b", 1.0),

            (r"\bblackmail\w*\b", 0.3),
            (r"\bextort\w*\b", 0.3),
            (r"\bfake\w*\b", 0.3),
            (r"\bmalpractic\w*\b", 0.3),
            (r"\bnegligenc\w*\b", 0.3),
            (r"\bethical\s+violat\w*\b", 0.3),
            #слова шумы
        (r"\brumour?\w*\b", -1.5),
        (r"\bhearsay\b", -1.5),
        (r"\bunconfirmed\b", -1.5),
        (r"\balleged\w*\b", -1.5),
        (r"\bwhisper\w*\b", -1.5),
        (r"\bgossip\w*\b", -1.5),
        (r"\bchatter\b", -1.5),

        (r"\bmight\b", -1.0),
        (r"\bcould\b", -1.0),
        (r"\bwould\b", -1.0),
        (r"\bshould\b", -1.0),
        (r"\bpossibly\b", -1.0),
        (r"\bpotentially\b", -1.0),
        (r"\bperhaps\b", -1.0),
        (r"\bmaybe\b", -1.0),
        (r"\bunlikely\b", -1.0),
        (r"\bdoubtful\b", -1.0),
        (r"\buncertain\w*\b", -1.0),

        (r"\bcommentary\b", -0.7),
        (r"\bopinion\w*\b", -0.7),
        (r"\bview\w*\b", -0.7),
        (r"\bperspective\w*\b", -0.7),
        (r"\boutlook\b", -0.7),
        (r"\bassessment\b", -0.7),
        (r"\bevaluation\b", -0.7),
        (r"\bappraisal\b", -0.7),

        (r"\bresistance\b", -0.5),
        (r"\bsupport\b", -0.5),
        (r"\bmoving average\b", -0.5),
        (r"\bRSI\b", -0.5),
        (r"\bMACD\b", -0.5),
        (r"\bBollinger\b", -0.5),
        (r"\bfibonacci\b", -0.5),
        (r"\bchart pattern\w*\b", -0.5),
        (r"\btechnical indicator\w*\b", -0.5),



        (r"\beventually\b", -0.3),
        (r"\bin the future\b", -0.3),
        (r"\bdown the road\b", -0.3),
        (r"\bin coming years\b", -0.3),
        (r"\blong.term\b", -0.3),
        (r"\bfuture prospect\w*\b", -0.3),
        (r"\bpotential growth\b", -0.3),
        ],

    "competitors": [
            (r"\bprice\s+war\w*\b", 3.0),
            (r"\bmarket\s+share\w*\b", 3.0),
            (r"\bcompetit\w*\b", 3.0),
            (r"\brival\w*\b", 3.0),
            (r"\bdomin\w*\b", 3.0),
            (r"\bovertak\w*\b", 3.0),
            (r"\bsurpass\w*\b", 3.0),
            (r"\bbeat\s+rival\w*\b", 3.0),
            (r"\blosing\s+market\b", 3.0),
            (r"\bgain\s+market\b", 3.0),

            (r"\bmonopol\w*\b", 1.0),
            (r"\boligopol\w*\b", 1.0),
            (r"\bmarket\s+disrupt\w*\b", 1.0),
            (r"\bpricing\s+strateg\w*\b", 1.0),
            (r"\bcompetitive\s+edge\b", 1.0),
            (r"\bcompetitive\s+advan\w*\b", 1.0),
            (r"\bretaliat\w*\b", 1.0),

            (r"\bundercut\w*\b", 0.3),
            (r"\bchallenge\w*\b", 0.3),
            (r"\bsubstitut\w*\b", 0.3),
            (r"\bnew\s+entrant\w*\b", 0.3),
            (r"\bcustomer\s+loss\w*\b", 0.3),
            (r"\bclient\s+switch\w*\b", 0.3),

            #слова шумы
        (r"\brumour?\w*\b", -1.5),
        (r"\bhearsay\b", -1.5),
        (r"\bunconfirmed\b", -1.5),
        (r"\balleged\w*\b", -1.5),
        (r"\bwhisper\w*\b", -1.5),
        (r"\bgossip\w*\b", -1.5),
        (r"\bchatter\b", -1.5),

        (r"\bmight\b", -1.0),
        (r"\bcould\b", -1.0),
        (r"\bwould\b", -1.0),
        (r"\bshould\b", -1.0),
        (r"\bpossibly\b", -1.0),
        (r"\bpotentially\b", -1.0),
        (r"\bperhaps\b", -1.0),
        (r"\bmaybe\b", -1.0),
        (r"\bunlikely\b", -1.0),
        (r"\bdoubtful\b", -1.0),
        (r"\buncertain\w*\b", -1.0),

        (r"\bcommentary\b", -0.7),
        (r"\bopinion\w*\b", -0.7),
        (r"\bview\w*\b", -0.7),
        (r"\bperspective\w*\b", -0.7),
        (r"\boutlook\b", -0.7),
        (r"\bassessment\b", -0.7),
        (r"\bevaluation\b", -0.7),
        (r"\bappraisal\b", -0.7),

        (r"\bresistance\b", -0.5),
        (r"\bsupport\b", -0.5),
        (r"\bmoving average\b", -0.5),
        (r"\bRSI\b", -0.5),
        (r"\bMACD\b", -0.5),
        (r"\bBollinger\b", -0.5),
        (r"\bfibonacci\b", -0.5),
        (r"\bchart pattern\w*\b", -0.5),
        (r"\btechnical indicator\w*\b", -0.5),



        (r"\beventually\b", -0.3),
        (r"\bin the future\b", -0.3),
        (r"\bdown the road\b", -0.3),
        (r"\bin coming years\b", -0.3),
        (r"\blong.term\b", -0.3),
        (r"\bfuture prospect\w*\b", -0.3),
        (r"\bpotential growth\b", -0.3),
        ]
}
max_chars = 10000

import re

df["content_clean"] = df["content"].str.lower()
df["content_clean"] = df["content_clean"].fillna("Текст не найден")
for category, patterns in categories.items():
    df[category] = df["content_clean"].apply(
        lambda text: sum(
            weight for pattern, weight in patterns
            if re.search(pattern, text[:max_chars])
        )
    )

df["title_clean"] = df["title"].str.lower()
for category, patterns in categories.items():
    df[category] += df["title_clean"].apply(
        lambda text: sum(
            weight * 2 for pattern, weight in patterns # вот здесь множитель веса для заголовка
            if re.search(pattern, text[:max_chars])
        )
    )

#print(sum(df['financial_results']))
print(len(df[df['financial_results']>0]))
#print(sum(df['product_launches']))
print(len(df[df['product_launches']>0]))
#print(sum(df['mergers_acquisitions']))
print(len(df[df['mergers_acquisitions']>0]))
#print(sum(df['regulatory_legal']))
print(len(df[df['regulatory_legal']>0]))
#print(sum(df['scandals']))
print(len(df[df['scandals']>0]))
#print(sum(df['competitors']))
print(len(df[df['competitors']>0]))

# @title
noise_words = {
    "speculation_rumors": [
        (r"\brumour?\w*\b", -1.5),
        (r"\bspeculat\w*\b", -1.5),
        (r"\bhearsay\b", -1.5),
        (r"\bunconfirmed\b", -1.5),
        (r"\balleged\w*\b", -1.5),
        (r"\bwhisper\w*\b", -1.5),
        (r"\bgossip\w*\b", -1.5),
        (r"\bchatter\b", -1.5),
    ],

    "uncertainty_hedging": [
        (r"\bmight\b", -1.0),
        (r"\bcould\b", -1.0),
        (r"\bwould\b", -1.0),
        (r"\bshould\b", -1.0),
        (r"\bpossibly\b", -1.0),
        (r"\bpotentially\b", -1.0),
        (r"\bperhaps\b", -1.0),
        (r"\bmaybe\b", -1.0),
        (r"\bunlikely\b", -1.0),
        (r"\bdoubtful\b", -1.0),
        (r"\buncertain\w*\b", -1.0),
    ],

    "analyst_commentary": [
        (r"\banalyst\w*\b", -0.7),
        (r"\bcommentary\b", -0.7),
        (r"\bopinion\w*\b", -0.7),
        (r"\bview\w*\b", -0.7),
        (r"\bperspective\w*\b", -0.7),
        (r"\boutlook\b", -0.7),
        (r"\bassessment\b", -0.7),
        (r"\bevaluation\b", -0.7),
        (r"\bappraisal\b", -0.7),
    ],

    "technical_analysis": [
        (r"\bresistance\b", -0.5),
        (r"\bsupport\b", -0.5),
        (r"\bmoving average\b", -0.5),
        (r"\bRSI\b", -0.5),
        (r"\bMACD\b", -0.5),
        (r"\bBollinger\b", -0.5),
        (r"\bfibonacci\b", -0.5),
        (r"\bchart pattern\w*\b", -0.5),
        (r"\btechnical indicator\w*\b", -0.5),
    ],

    "future_potential": [
        (r"\beventually\b", -0.3),
        (r"\bin the future\b", -0.3),
        (r"\bdown the road\b", -0.3),
        (r"\bin coming years\b", -0.3),
        (r"\blong.term\b", -0.3),
        (r"\bfuture prospect\w*\b", -0.3),
        (r"\bpotential growth\b", -0.3),
    ],

}